enable_host_api_key: True
embedding_options:
  persist_directory: False # str or None
  db_option : 'FAISS'
  model : 'text-embedding-ada-002'
llm: 'gpt-3.5-turbo-1106'
splitter_options:
  use_splitter: True
  remove_leftover_delimiters: True
  remove_pages: False
  chunk_size : 800
  chunk_overlap : 80
  chunk_separators : ['\n\n', '. ']
  front_pages_to_remove : None # int or None
  last_pages_to_remove : None # int or None
  delimiters_to_remove : ['\t', '\n', '   ', '  '] #list of strings
